services:
  go-util:
    container_name: auth-dev 
    volumes:
      - ./:/app:rw
      - ./nvim:/root/.config/nvim
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env 
    ports:
      - "8001:8000"
    tty: true
    stdin_open: true
  state-store:
    container_name: redis_state 
    image: redis:7.4-alpine 
    ports:
      - "6379:6379"
    command: --loglevel warning 
    

